services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: anki-lang-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: anki-lang-client
    ports:
      - "3000:80"