# This Dockerfile builds the API only.

FROM python:3.9
WORKDIR /app

COPY api/requirements.txt api/.flaskenv ./
COPY api/api.py ./api/
COPY api/scrapers ./api/scrapers
COPY api/utils ./api/utils
COPY api/__init__.py ./api

RUN mkdir audio_files
RUN mkdir zip_files

RUN pip install -r requirements.txt

ENV FLASK_ENV production

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000", "api.api:app"]
