services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: anki-lingo-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: anki-lingo-client
    ports:
      - "8080:80"