services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: anki-lang-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: anki-lang-client
    ports:
      # Set to "3000:80" when running locally, "80:80" for hosting with elastic beanstalk
      - "3000:80"