name: Deploy to EC2

on:
  push:
    branches:
      - main
      - feat/ip-v6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Clean EC2 app directory
      run: |
        ssh -6 -o StrictHostKeyChecking=no ec2-user@2600:1f18:6d2d:76e8:dc80:b527:6ad9:39ff 'rm -rf /home/ec2-user/app/*'

    - name: Copy files to EC2
      run: |
        scp -6 -o StrictHostKeyChecking=no -r * ec2-user@2600:1f18:6d2d:76e8:dc80:b527:6ad9:39ff:/home/ec2-user/app
    
    - name: SSH into EC2 and deploy
      run: |
        ssh -6 -o StrictHostKeyChecking=no ec2-user@2600:1f18:6d2d:76e8:dc80:b527:6ad9:39ff << EOF
          cd /home/ec2-user/app
          docker-compose down
          docker system prune -f --volumes
          docker-compose up -d --build
        EOF
