name: Deploy to EC2

on:
  push:
    branches:
      - main
      - feat/ip-v6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Test DNS and IPv6 connectivity (optional, remove after testing)
      run: |
        nslookup anki.taylorbarmak.com
        ping6 -c 3 anki.taylorbarmak.com || echo "Ping6 failed"
        ssh -6 -o StrictHostKeyChecking=no ec2-user@anki.taylorbarmak.com 'echo Connected via IPv6'

    - name: Clean EC2 app directory
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@anki.taylorbarmak.com 'rm -rf /home/ec2-user/app/*'

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r * ec2-user@anki.taylorbarmak.com:/home/ec2-user/app

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@anki.taylorbarmak.com << EOF
          cd /home/ec2-user/app
          docker-compose down
          docker system prune -f --volumes
          docker-compose up -d --build
        EOF
